service: mitali-sls
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  role: arn:aws:iam::546628620317:role/LabRole
  region: us-east-1

functions:
  createPaymentOrder:
    handler: handler.createPaymentOrder
    events:
      - http:
          path: create-payment-order
          method: post
          cors: true

  verifyPayment:
    handler: handler.verifyPayment
    events:
      - http:
          path: verify-payment
          method: post
          cors: true


  renderhome:
    handler: handler.homepage
    events:
      - http:
          path: homepage
          method: get
          cors: true

  rendercourse:
    handler: handler.coursepage
    events:
      - http:
          path: course
          method: post
          cors: true

  registerUser:
    handler: handler.registerUser
    events:
      - http:
          path: register
          method: post
          cors: true

  loginUser:
    handler: handler.loginUser
    events:
      - http:
          path: login
          method: post
          cors: true
          
  logoutUser:
    handler: handler.logouthandler
    events:
      - http:
          path: logout
          method: post
          cors: true

  checkloginStatus:
    handler: handler.check
    events:
      - http:
          path: fetching
          method: post
          cors: true
          
  generatePresignedUrl:
    handler: handler.generatePresignedUrl
    events:
      - http:
          path: videos/presigned-url
          method: post
          cors: true      

  removeExpiredCourses:
    handler: handler.removeExpiredCourses
    events:
      - http:
          path: remove-expired-courses
          method: post
          cors: true
      - schedule: rate(1 day)        